---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: web
        path: /mutate-buildcrd-k8s-example-io-v1-app
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwVENDQWJtZ0F3SUJBZ0lRZVdsTVdDMk1XMWVNZUR3VDd0azU0akFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSTBNRFF5TmpBMk1UY3pNRm9YRFRJME1EY3lOVEEyTVRjek1Gb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG5ZZndhNGZHbXkvNk5tTGdQMHhzaGJPY3ZPcGVNaS84UnZrY1MyCmJLdzVVZTEwNEI5Q3JlTmdvRHJvNDZUR2dOT2VRUEpqT1Jma1hlQURBZjZCN1FrbXVGRW9oWkpHN3dUTm9pbXoKV29qKzB0ckhTdkUzNXdZWVEwK1NydEZUcDNXd09MSXpnWjZEQm40d3k0eUtCTlhDbDNxcVJSbWpZc1FVZVBoRwo1am1vWkhwYXlHVHhOSmI2N3gxVnF0TE9uditYM2NQdDNtYWhNN1ZRQm9YK2l3NlQrZzVib2tWQ2l0VTFBa1JECjh1L1VxYWcydHpYOS9OZUVmZk94S1dCL2NqdHNqdk53aGFuV2Q5MitzZ0pkWVArWEZBME9Xbmt2WnVDREs5eDcKUkUxK1o5SG5NTVliR1FjOVpRWW5rbUVoYTBpNm53WjJOU1B1eVRiblZmalNjeDhDQXdFQUFhTkhNRVV3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUF3R0ExVWRFd0VCL3dRQ01BQXdKUVlEVlIwUkFRSC9CQnN3R1lJWGQyVmlhRzl2CmF5MXpaWEoyYVdObExuZGxZaTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIcStLcTI3bXd2dVZvanAKWmh4ODd1NWZzb2RZQVpZMml5MVU0cGJvTXIyazRRaTNyUGp2Zm5jWVU5aENrbmhvOVVYUGc3TFQ4WWM1VXN5OQozb2hGN3U2QXV6dzJLOXpJcCt1aHVZNy9qQ20rUXlERm9IR1AxOURVYk9RdXBlQTRoRnM3VWJRRE9aRWlWZTJnCm9aMWR6V0J6RFJiVVpCbkxtMmpLVmp6VWk2ZDd6WCtoQUFYQjdsN0VscVNlK3A5LzJtMGM1RFlBLzcyWHMvdDQKeHEwN1pDajlyUThXdGlMWmVDU0duL0RuZjlkOHdDUWk2S1Z2d3dVdW1USnpWZkNRa0lJNTBrUjhGTkVlRHJyRQpVQVN1a2ZJUVhlUXVhQUVPRWpHK1FtT3BNTjNXTTh6d2NZcW5YaE9KMC9zNmtUM3B4QjdGVXNwemVKNFEvcm1OCjZ2N3B4QmM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    failurePolicy: Fail
    name: mapp.kb.io
    rules:
      - apiGroups:
          - buildcrd.k8s.example.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - apps
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: web
        path: /validate-buildcrd-k8s-example-io-v1-app
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwVENDQWJtZ0F3SUJBZ0lRZVdsTVdDMk1XMWVNZUR3VDd0azU0akFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSTBNRFF5TmpBMk1UY3pNRm9YRFRJME1EY3lOVEEyTVRjek1Gb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG5ZZndhNGZHbXkvNk5tTGdQMHhzaGJPY3ZPcGVNaS84UnZrY1MyCmJLdzVVZTEwNEI5Q3JlTmdvRHJvNDZUR2dOT2VRUEpqT1Jma1hlQURBZjZCN1FrbXVGRW9oWkpHN3dUTm9pbXoKV29qKzB0ckhTdkUzNXdZWVEwK1NydEZUcDNXd09MSXpnWjZEQm40d3k0eUtCTlhDbDNxcVJSbWpZc1FVZVBoRwo1am1vWkhwYXlHVHhOSmI2N3gxVnF0TE9uditYM2NQdDNtYWhNN1ZRQm9YK2l3NlQrZzVib2tWQ2l0VTFBa1JECjh1L1VxYWcydHpYOS9OZUVmZk94S1dCL2NqdHNqdk53aGFuV2Q5MitzZ0pkWVArWEZBME9Xbmt2WnVDREs5eDcKUkUxK1o5SG5NTVliR1FjOVpRWW5rbUVoYTBpNm53WjJOU1B1eVRiblZmalNjeDhDQXdFQUFhTkhNRVV3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUF3R0ExVWRFd0VCL3dRQ01BQXdKUVlEVlIwUkFRSC9CQnN3R1lJWGQyVmlhRzl2CmF5MXpaWEoyYVdObExuZGxZaTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIcStLcTI3bXd2dVZvanAKWmh4ODd1NWZzb2RZQVpZMml5MVU0cGJvTXIyazRRaTNyUGp2Zm5jWVU5aENrbmhvOVVYUGc3TFQ4WWM1VXN5OQozb2hGN3U2QXV6dzJLOXpJcCt1aHVZNy9qQ20rUXlERm9IR1AxOURVYk9RdXBlQTRoRnM3VWJRRE9aRWlWZTJnCm9aMWR6V0J6RFJiVVpCbkxtMmpLVmp6VWk2ZDd6WCtoQUFYQjdsN0VscVNlK3A5LzJtMGM1RFlBLzcyWHMvdDQKeHEwN1pDajlyUThXdGlMWmVDU0duL0RuZjlkOHdDUWk2S1Z2d3dVdW1USnpWZkNRa0lJNTBrUjhGTkVlRHJyRQpVQVN1a2ZJUVhlUXVhQUVPRWpHK1FtT3BNTjNXTTh6d2NZcW5YaE9KMC9zNmtUM3B4QjdGVXNwemVKNFEvcm1OCjZ2N3B4QmM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    failurePolicy: Fail
    name: vapp.kb.io
    rules:
      - apiGroups:
          - buildcrd.k8s.example.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - apps
    sideEffects: None
