---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: web
rules:
  - apiGroups: [ "", "apps" ]
    resources: [ "services", "deployments" ]
    verbs: [ "get", "list", "watch", "create", "update", "delete", "patch" ]
  - apiGroups: [ "buildcrd.k8s.example.io" ]
    resources: [ "apps" ]
    verbs: [ "get", "list", "watch", "create", "update", "delete", "patch" ]
  - apiGroups: [ "buildcrd.k8s.example.io" ]
    resources: [ "apps/finalizers" ]
    verbs: [ "update" ]
  - apiGroups: [ "buildcrd.k8s.example.io" ]
    resources: [ "apps/status" ]
    verbs: [ "get", "patch", "update" ]

