# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.buildcrd.k8s.example.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: web
          name: web-webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
      - v2
