apiVersion: buildcrd.k8s.example.io/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: kubebuild-go
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  # TODO(user): Add fields here
