apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.ObjectMeta.Name}}-ingress
  namespace: {{.ObjectMeta.Namespace}}
spec:
  ingressClassName: nginx
  rules:
    - host: {{.ObjectMeta.Name}}.crdController.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.ObjectMeta.Name}}-service
                port:
                  number: 80
  