apiVersion: v1
kind: Service
metadata:
  name: {{.ObjectMeta.Name}}-svc
  namespace: {{.ObjectMeta.Namespace}}
spec:
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: {{.ObjectMeta.Name}}-app